---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks
- Quick:
    - GMail:
        - icon: gmail.svg
          href: https://gmail.com
          target: _self
          description: Where important emails hide in plain sight
    - YouTube:
        - icon: youtube.svg
          href: https://youtube.com
          target: _self
          description: A 2-minute tutorial turns into a 2-hour binge
    - Twitch.TV:
        - icon: twitch.svg
          href: https://twitch.tv
          target: _self
          description: Watch people play games you already own
    - Facebook:
        - icon: facebook.svg
          href: https://www.facebook.com
          target: _self
          description: Where your aunt shares cat memes
    - Instagram:
        - icon: instagram.svg
          href: https://www.instagram.com
          target: _self
          description: Where life looks better with a filter
    - X:
        - icon: x.svg
          href: https://www.x.com
          target: _self
          description: Everyone is a philosopher, journalist, and comedian
    - Amazon:
        - icon: amazon.svg
          href: https://www.amazon.com
          target: _self
          description: Online Shopping Monopoly
- IT:
    - Hostinger:
        - abbr: H
          href: https://hpanel.hostinger.com
          target: _self
          description: Web Hosting
    - Cloudflare:
        - icon: cloudflare.svg
          href: https://dash.cloudflare.com/a4fa935cbb3abd0d28a17d26b5f17ec3
          target: _self
          description: SSL and Stuff
    - Reddit:
        - icon: reddit.png
          href: https://www.reddit.com
          target: _self
          description: Where experts, trolls, and meme lords unite
    - ChatGPT:
        - icon: chatgpt.svg
          href: https://chat.openai.com
          target: _self
          description: Chat Bot
    - LXC Scripts:
        - icon: github.svg
          href: https://helper-scripts.com/scripts
          target: _self
          description: Proxmox VE Helper Scripts
    - Dashboard Icons:
        - icon: github.svg
          href: https://github.com/walkxcode/dashboard-icons
          target: _self
          description: Icon Repository
- Gaming:
    - Twitch Dashboard:
        - icon: twitch.svg
          href: https://dashboard.twitch.tv/u/itsmedeimo/stream-manager
          target: _self
          description: My Twitch Dashboard
    - NoPixel:
        - icon: https://nopixel-minigames.vercel.app/_next/image?url=%2Fnopixel-logo.png&w=64&q=75
          href: https://www.nopixel.net
          target: _self
          description: NoPixel GTA RP
    - HasRoot:
        - icon: https://nopixel.hasroot.com/apple-touch-icon.png
          href: https://nopixel.hasroot.com/
          target: _self
          description: NoPixel Streams
    - StreamElements:
        - icon: https://cdn-images-1.medium.com/v2/resize:fit:1200/1*8npdfsLSO776rf90SIX5pg.png
          href: https://streamelements.com/
          target: _self
          description: StreamElements
    - Fiverr:
        - abbr: F
          href: https://www.fiverr.com
          target: _self
          description: Hire someone to design your logo, write your jingle, or train your cat
