title: Deimo's Homepage
headerStyle: clean
background:
  image: https://kappa.lol/tJW_3.jpeg
  blur: md
  saturate: 50
  brightness: 50
  opacity: 70
theme: dark
color: slate
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: false
layout:
  Quick:
    header: false
    style: column
  IT:
    header: false
    style: column
  Gaming:
    header: false
    style: column
  Calendar:
    header: false
    style: column
  Monitor:
    header: true
    style: row
    columns: 3
  Local Services:
    header: true
    style: column
    columns: 4
  Cloud:
    header: true
    style: column
    columns: 4
  WhatBox:
    header: true
    style: column
    columns: 4