---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- openmeteo:
    label: Riverside # optional
    latitude: 33.98054
    longitude: 117.37701
    timezone: America/Los_Angeles # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 0

#- resources:
 #   cpu: true
  #  memory: true
   # disk: /

- search:
    provider: google
    target: _blank
    focus: true
    showSearchSuggestions: true

- openmeteo:
    label: Χαλκίδα # optional
    latitude: 38.4687
    longitude: 23.6229
    timezone: Europe/Athens # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 0